name: Close Actions

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-close-actions.yml@845e392790542cd3f46c65785222e341b4d2f0e1 # v2.4.1
    permissions:
      issues: write
      pull-requests: write
      actions: write
