name: Close Actions

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-close-actions.yml@36c7e2a2d20f2617610ed1d4c15c9e83f156d961 # v2.5.0
    permissions:
      issues: write
      pull-requests: write
      actions: write
