name: Enforce conventions

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-conventions.yml@36c7e2a2d20f2617610ed1d4c15c9e83f156d961 # v2.5.0
    permissions:
      issues: write
      pull-requests: write
