name: Enforce conventions

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-conventions.yml@30672d8a7c23d5931f89360cc50ce44a81337755 # v2.5.1
    permissions:
      issues: write
      pull-requests: write
