name: Enforce conventions

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-conventions.yml@5a0a828ec10bcebf7c980d13fca16f99be69f6d0 # v2.4.0
    permissions:
      issues: write
      pull-requests: write
