name: Sync webhook

on:
  schedule:
    - cron: "0 3 * * 0"
  push:
    branches: [main]
    paths: [.github/workflows/sync-webhook.yml]
  workflow_dispatch:

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-sync-webhook.yml@845e392790542cd3f46c65785222e341b4d2f0e1 # v2.4.1
    with:
      bot-app-id: ${{ vars.RUBBERDUCKCREW_BOT_APP_ID }}
    secrets:
      BOT_APP_PRIVATE_KEY: ${{ secrets.RUBBERDUCKCREW_BOT_APP_PRIVATE_KEY }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
