name: Sync labels

on:
  schedule:
    - cron: "0 3 * * 0"
  push:
    branches: [main]
    paths: [.github/workflows/sync-labels.yml]
  workflow_dispatch:

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-sync-labels.yml@9359cf3f39584573a76ae17b2efc76b192c5050e # v2.3.0
    permissions:
      issues: write
