name: Sync webhook

on:
  schedule:
    - cron: "0 3 * * 0"
  push:
    branches: [main]
    paths: [.github/workflows/sync-webhook.yml]
  workflow_dispatch:

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-sync-webhook.yml@36c7e2a2d20f2617610ed1d4c15c9e83f156d961 # v2.5.0
    with:
      bot-app-id: ${{ vars.RUBBERDUCKCREW_BOT_APP_ID }}
    secrets:
      BOT_APP_PRIVATE_KEY: ${{ secrets.RUBBERDUCKCREW_BOT_APP_PRIVATE_KEY }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
