name: Sync labels

on:
  schedule:
    - cron: "0 3 * * 0"
  push:
    branches: [main]
    paths: [.github/workflows/sync-labels.yml]
  workflow_dispatch:

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-sync-labels.yml@5a0a828ec10bcebf7c980d13fca16f99be69f6d0 # v2.4.0
    permissions:
      issues: write
