name: Sync labels

on:
  schedule:
    - cron: "0 3 * * 0"
  push:
    branches: [main]
    paths: [.github/workflows/sync-labels.yml]
  workflow_dispatch:

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-sync-labels.yml@30672d8a7c23d5931f89360cc50ce44a81337755 # v2.5.1
    permissions:
      issues: write
